### ISSUE TITLE
Integrate OpenFaas client with AtomDB

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-infra-stack-vultr#4]

**Comment by levisingularity** [comment]
@andre-senna i've integrated the openfaas with the atomdb, just need to know where I should place the client source code

**Comment by levisingularity** [comment]
@andre-senna PRs: https://github.com/singnet/das-servless-functions/pull/1 & https://github.com/singnet/das-infra-stack-vultr/pull/5
